### ISSUE TITLE
dyld:Library not loaded:/System/Library/Frameworks/MetalKit.framework/MetalKit Crashed on iOS8

### ISSUE THREAD

**Issue by CoderXLL** [zevarito/PodRTC#4]
What steps will reproduce the problem?
1.build is OK
2.but i found after version M58, run on iOS8 devive error:
dyld:Library not loaded:/System/Library/Frameworks/MetalKit.framework/MetalKit
Referenced from:/private/var/mobile/Containers/Bundle/Application/...
Reason:image not found
the version M58 is OK!
the newer always run error on iOS8 device

**Comment by 983563622** [comment]
I met the same problem!

**Comment by zevarito** [comment]
@b593771943 @BossKing can you copy the exact version/tag that you are using and a snippet code to trigger the issue so I can test it myself ?

**Comment by zevarito** [comment]
Also IOS8 device, what version exactly?

**Comment by 983563622** [comment]
after M58 version is run error, but M58 is fine,My device is iOS8.3 iPhone6, you can use my project(https://github.com/BossKing/BKWebRTC) with CocoaPods to find the problem!

**Comment by 983563622** [comment]
this is the official answer: https://bugs.chromium.org/p/webrtc/issues/detail?id=7899#c3

**Comment by zevarito** [comment]
IOS8 is not supported on recent versions seriously?

Since there are probably tons of IOS8 devices out-there could be nice to create a new r58 build patched with the issues that's has been fixed on future versions but not back-ported.
Please add to this thread an issue/link that you think have not been back-ported to r58 and needs to be included.
