### ISSUE TITLE
there is no RTCAudioSession class in framework

### ISSUE THREAD

**Issue by smolskyaleksey** [zevarito/PodRTC#5]
There is no RTCAudioSession class in framework. I can't use CallKIt because I have to use methods from RTCAudioSession.

**Comment by zevarito** [comment]
WebRTC Framework is bundled without RTCAudioSession, did you ask why/how on WebRTC discussion list or bug tracker?

I could add the following files by hand, but not sure how that will work.
```
webrtc/modules/audio_device/ios/objc/RTCAudioSession.h
webrtc/modules/audio_device/ios/objc/RTCAudioSessionConfiguration.h
webrtc/modules/audio_device/ios/objc/RTCAudioSessionDelegateAdapter.h
```

**Comment by smolskyaleksey** [comment]
Could you add. I will try to check. I want to know why your framework doesn't have RTCAudioSession?

**Comment by zevarito** [comment]
The way I compile the library is pretty much straight forward, its only purpose is to wrap it in a pod, I think you should ask on the official channels why it is out, may be it is out just because there is a high level API for that?, don't know. Meanwhile I'll do a new build with those headers and put it in a branch so you can try.

**Comment by zevarito** [comment]
@smolskyaleksey let me know how it works
https://github.com/zevarito/PodRTC/tree/exposed_rtc_audio_session

**Comment by smolskyaleksey** [comment]
It works! Thx.
